### PR TITLE
Allow for option to bypass query escaping the auth header credentials

### PR DESCRIPTION
**Pull request by mwielbut**
Some (many, it seems) OAuth providers do not adhere to the standard of accepting query escaped credentials. If your client ID or client secret contains non-URL query characters they will be rejected by the OAuth provider.
The current implementation always query escapes the `client_id` and `client_secret`:
`req.SetBasicAuth(url.QueryEscape(clientID), url.QueryEscape(clientSecret))`
This PR proposes the ability the register an auth provider that does not escape the header and bypasses the escaping. 
`func RegisterNonQueryEscapedAuthHeaderProvider(tokenURL string)`
and
```
if nonEscapableAuth {
	req.SetBasicAuth(clientID, clientSecret)
} else {
	req.SetBasicAuth(url.QueryEscape(clientID), url.QueryEscape(clientSecret))
}
```
This has been raised several times:
https://github.com/golang/oauth2/issues/251
https://github.com/golang/oauth2/issues/318
https://github.com/golang/oauth2/issues/320
but without this feature this library cannot be used against some key OAuth providers.

We already have the ability to bypass the header authentication for OAuth providers that require a `client_id` and `client_secret` be passed as parameters--this builds on that.

### CODE REVIEW

**Comment by mwielbut** [comment]
CLA signed.

**Comment by dmgcodevil** [comment]
any plans on merging this PR ?

**Comment by efimovalex** [comment]
any plans for releasing this change?

**Comment by alupuleasa** [comment]
Will this PR ever by merged?

**Comment by mwielbut** [comment]
Closing in favor of https://github.com/golang/oauth2/pull/476

**Pull request closed without merging**
